print("luz roja encendida")
print("esperar 20 segundos para apagar")
print("luz roja apagada")
print("luz amarilla encendida")
print("esperar 5 segundos")
print("luz amarilla apagada")
print("luz verde encendida")
print("esperar 40 segundos")
print("encender luz amarilla junta luz verde")
print("esperar 5 segundos")
print("apagar luces amarilla y verde")
print("se repite el ciclo")